/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiposdetriangulo;

/**
 *
 * @author gabri
 */
public class TiposdeTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form TiposdeTriangulo
     */
    public TiposdeTriangulo() {
        initComponents();
        panTriangulo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slider1 = new javax.swing.JSlider();
        slider2 = new javax.swing.JSlider();
        slider3 = new javax.swing.JSlider();
        lblNum1 = new javax.swing.JLabel();
        lblNum3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNum2 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        panTriangulo = new javax.swing.JPanel();
        lblFormatri = new javax.swing.JLabel();
        lblTipotri = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Seguimento A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 62, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Seguimento B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 101, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Seguimento C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 140, -1, -1));

        slider1.setMaximum(20);
        slider1.setValue(0);
        slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider1StateChanged(evt);
            }
        });
        getContentPane().add(slider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 62, 120, 21));

        slider2.setMaximum(20);
        slider2.setValue(0);
        slider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider2StateChanged(evt);
            }
        });
        getContentPane().add(slider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 101, 120, 21));

        slider3.setMaximum(20);
        slider3.setValue(0);
        slider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider3StateChanged(evt);
            }
        });
        getContentPane().add(slider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 140, 121, 14));

        lblNum1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNum1.setText("0");
        getContentPane().add(lblNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 62, -1, -1));

        lblNum3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNum3.setText("0");
        getContentPane().add(lblNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 140, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/triangulo.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        lblNum2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNum2.setText("0");
        getContentPane().add(lblNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 101, -1, -1));

        btnVerificar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 199, -1, -1));

        lblFormatri.setFont(new java.awt.Font("Comic Sans MS", 0, 19)); // NOI18N
        lblFormatri.setForeground(new java.awt.Color(0, 0, 204));
        lblFormatri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormatri.setText("0");

        lblTipotri.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        lblTipotri.setForeground(new java.awt.Color(255, 0, 0));
        lblTipotri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipotri.setText("0");

        javax.swing.GroupLayout panTrianguloLayout = new javax.swing.GroupLayout(panTriangulo);
        panTriangulo.setLayout(panTrianguloLayout);
        panTrianguloLayout.setHorizontalGroup(
            panTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTrianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormatri, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(lblTipotri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panTrianguloLayout.setVerticalGroup(
            panTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTrianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormatri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lblTipotri)
                .addContainerGap())
        );

        getContentPane().add(panTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 230, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider1StateChanged
        // TODO add your handling code here:
        lblNum1.setText (Integer.toString(slider1.getValue()));
    }//GEN-LAST:event_slider1StateChanged

    private void slider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider2StateChanged
        // TODO add your handling code here:
        lblNum2.setText(Integer.toString(slider2.getValue()));
    }//GEN-LAST:event_slider2StateChanged

    private void slider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider3StateChanged
        // TODO add your handling code here:
        lblNum3.setText(Integer.toString(slider3.getValue()));
    }//GEN-LAST:event_slider3StateChanged

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        panTriangulo.setVisible(true);
        
        int a = slider1.getValue();
        int b = slider2.getValue();
        int c = slider3.getValue();
        
        if(a<b+c && b<a+c && c<a+b){
            lblFormatri.setText("Forma um triângulo");
            if (a == b && b == c){
                lblTipotri.setText("Equilátero");
                
            }else if (a != b && a == c || b == c && b != a || c == a && c!= b || a==b && a != c){
                lblTipotri.setText("Isósceles");
                
            }else if (a != b && b!= c){
                lblTipotri.setText("Escaleno");
            }
        }else{
            lblFormatri.setText("Não forma um triângulo");
            lblTipotri.setText("----------");
        }
        
    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiposdeTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiposdeTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiposdeTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiposdeTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiposdeTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblFormatri;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JLabel lblNum3;
    private javax.swing.JLabel lblTipotri;
    private javax.swing.JPanel panTriangulo;
    private javax.swing.JSlider slider1;
    private javax.swing.JSlider slider2;
    private javax.swing.JSlider slider3;
    // End of variables declaration//GEN-END:variables
}
